#pragma once

#include "FurnitureMark.hpp"
#include "Gamebryo/NiPoint3.hpp"
#include "MiddleLowProcess.hpp"

class QueuedFile;
class QueuedItem;
class NiNode;
class MagicItem;
class BSFaceGenAnimationData;
class MagicTarget;
class Animation;
class BSAnimGroupSequence;
class BSBound;
class BSFaceGenNiNode;
class NiTriShape;
class PatrolActorPackageData;
class BSCloneReserver;

NiSmartPointer(BSShaderPPLightingProperty);

class MiddleHighProcess : public MiddleLowProcess {
public:
	MiddleHighProcess();
	~MiddleHighProcess();

	virtual void	SetAnimation(Animation* apAnimation);
	virtual bool	SetupPathFinding(Actor* apActor, NiPoint3 akTargetPos, TESObjectCELL* apTargetCell, TESWorldSpace* apTargetWorld);
	virtual void	SetAnimationActiveFlag(bool abActivate);
	virtual void	SetPackageTarget();
	virtual void	ProcessBuyObject(Actor* apActor);
	virtual void	ProcessSteal(Actor* apActor);
	virtual void	ProcessPickpocket(Actor* apActor);
	virtual void	ProcessDialogue(Actor* apActor);
	virtual void	ProcessDialogueActivate(Actor* apActor);
	virtual bool	ProcessUseFurniture(Actor* apActor, TESObjectREFR* apFurniture);
	virtual void	ProcessRemoveWornAlt(Actor* apActor, bool abIterateIndex, bool);
	virtual void	ProcessWander(Actor* apActor, NiPoint3* apPos, float afRadius = -1.f);
	virtual bool	ProcessSandboxDialogue(Actor* apActor, TESObjectREFR* apTarget);
	virtual void	Patrol_Start(Actor* apActor, PatrolActorPackageData* apData);
	virtual void	Patrol_StartTravelToRef(Actor* apActor, PatrolActorPackageData* apData);
	virtual void	Patrol_TravelingToNextRef(Actor* apActor, PatrolActorPackageData* apData);
	virtual void	Patrol_StartAtRefBehavior(Actor* apActor, PatrolActorPackageData* apData);
	virtual void	Patrol_AtRef(Actor* apActor, PatrolActorPackageData* apData);
	virtual void	ProcessUseIdleMarker(Actor* apActor, TESObjectREFR* apTarget);
	virtual bool	ProcessAccompanyOneHour(Actor* apActor);

	BSSimpleList<TESObjectREFR*>		kDetectedDead;
	BSSimpleList<TESObjectREFR*>		kChairAndBeds;
	float								fPursueTimer;
	float								fEquippedWeight;
	bool								bIdleDoneOnce;
	bool								bAimingTarget;
	bool								bUnkE2;
	bool								bUnkE3;
	ActorPackage						kRunOncePackage;
	NiPoint3							kLastSeenTargetPosition;
	uint32_t							eUseItem;
	TESIdleForm*						pLastPlayedIdle;
	bool								bResetPackageIdleTimer;
	ItemChange*							pCurrentWeapon;
	ItemChange*							pCurrentAmmo;
	NiPointer<QueuedFile>				spQueuedFile;
	NiPointer<BSCloneReserver>			spCloneReserver;
	bool								bIsUsingOneHandGrenade;
	bool								bIsUsingOneHandMine;
	bool								bIsUsingOneHandThrown;
	bool								bIsWearingHeavyArmor;
	bool								bIsWearingPowerArmorTorso;
	bool								bIsWearingPowerArmorHelmet;
	bool								bIsWearingBackpack;
	NiNode*								pWeaponNode;
	NiNode*								pProjectileNode;
	bool								bWantWeaponDrawn;
	bool								bWeaponDrawn;
	NiPointer<bhkCharacterController>	spCharCtrl;
	uint8_t								eKnockedState;
	uint8_t								eSitSleepState;
	TESObjectREFR*						pCurrentFurniture;
	uint8_t								ucCurrentFurnitureIndex;
	FurnitureMark						kFurnitureMark;
	Actor*								pCommandingActor;
	TESObjectWEAP*						pLastBoundWeapon;
	MagicItem*							pCurrentSpell;
	MagicItem*							pCurrentPackageSpell;
	bool								bCheckMagicNode;
	TESEffectShader*					pCurrentWeaponEffect;
	float								fAlphaMult;
	float								fScriptRefractPower;
	BSFaceGenAnimationData*				pFaceAnimationData;
	bool								bRefreshMagicShaderEffects;
	bool								bInitializeActiveHitEffect;
	bool								bUpdateWeaponEffectShader;
	bool								byte17F;
	bool								bRefreshFlareFlags;
	Bitfield32							uiFlareFlags;
	bool								bPickPocketed;
	bool								bDoneClothesChange;
	bool								bDetectLifeDetected;
	bool								bIsSummonedCreature;
	Bitfield<_Update3DFlags>			uc3DUpdateFlags;
	bool								bForceNextUpdate;
	uint32_t							iPackageIdleNumber;
	TESIdleForm*						pCurrentIdle;
	float								fPackageIdleTimer;
	bool								bPlayedBeginIdles;
	bool								bPlayedEndIdles;
	uint32_t							lipSyncAnim1A0;
	uint32_t							unk1A4;
	uint32_t							iReservationSlot;
	BSSimpleList<ArrowProjectile*>*		pAttachedArrows;
	BSSimpleList<void*>					kDeferredLimbHideList;
	BSSimpleList<ActiveEffect*>*		pActiveEffects;
	MagicTarget*						pDesiredTarget;
	Animation*							pAnimation;
	BSAnimGroupSequence*				pWeaponSequences[3];
	float								fAimChaseLookAngle;
	float								fAttackLoopTime;
	uint8_t								ucShotsToFire;
	bool								bIsFiringAutomaticWeapon;
	bool								bBeenAttacked;
	NiNode*								pLimbNodes[15];
	NiNode*								pHeadNode;
	NiNode*								pTorsoNode;
	BSShaderPPLightingPropertyPtr		spLightingProperty;
	BSBound*							pBoundingBox;
	bool								bIsAiming;
	bool								byte229;
	uint16_t							byte22A_shouldEnterFurniture;
	uint32_t							unk22C;
	BSSimpleList<QueuedItem*>*			pQueuedItems;
	float								fAmbientRadiation;
	float								fEffectRadiation;
	float								fWaterRadiation;
	HitData*							pLastHitData;
	uint32_t							uiWeaponHealth;
	BSFaceGenNiNode*					pFaceGenNiNodeBiped;
	BSFaceGenNiNode*					pFaceGenNiNodeSkinned;
	NiTriShape*							pFaceGenHeadAnims;
	HitData*							pLastTargetHitData;
	uint32_t							uiLastChairBedScan;
};

ASSERT_SIZE(MiddleHighProcess, 0x25C);